### ISSUE TITLE
assert.h conflict with Xcode use_headermap

### ISSUE THREAD

**Issue by ph4r05** [datatheorem/TrustKit#150] opened 2017-11-18 12:38 UTC
Hi, 

I've been experiencing the following build problem after adding this library via cocoa pods.

The TrustKit contains [assert.h](https://github.com/datatheorem/TrustKit/blob/7bdaf02200f5b35203d1321515b15ea498c38323/TrustKit/Dependencies/domain_registry/private/assert.h) file. XCode by default has 
set `USE_HEADERMAP=YES`. It builds a mapping on the header files enabling simple imports without need to follow directory structure or set include paths.

My project is quite big and was build with this XCode settings enabled. I am also using another thirdparty library which includes the system `<assert.h>`. But after adding TrustKit the `assert.h` is ambiguous and conflicts with the system one. This causes my build to fail.

One workaround would be to set `USE_HEADERMAP=NO` but then I would have to refactor my whole project and use either relative import paths everywhere or configure all include paths.

I was wondering whether you could possibly rename this header file so it does not conflict with the system one.

Thanks!

**Comment by nabla-c0d3** [comment] 2017-11-18 19:00
Good catch and this looks like the root cause of #148. We'll take care of it.

**Comment by nabla-c0d3** [comment] 2017-11-28 01:59
Fixed in 1.5.2.

**Closed by nabla-c0d3** 2017-11-28 01:59 UTC
