### ISSUE TITLE
Appears broken on iOS 9.

### ISSUE THREAD

**Issue by iragsdale** [datatheorem/TrustKit#18] opened 2015-08-31 21:25 UTC
I can verify that it does go through the configuration process and attempt to hook into the SSLHandshake method, however it never appears to call the replaced_SSLHandshake method. Perhaps fishhook doesn't quite work correctly on iOS 9? I went and downloaded the current version of fishhook.c as of today, and it makes no difference.

Perhaps that method is now lazy loaded? https://github.com/facebook/fishhook/issues/10

**Comment by nabla-c0d3** [comment] 2015-08-31 21:31
Hi and thanks for having a look. Which version of TrustKit did you use ? We just updated (today) the one on CocoaPods to 1.1.3, which we've successfully tested on iOS 9. Any previous version does not work on iOS 9.

**Comment by iragsdale** [comment] 2015-08-31 21:32
I updated to 1.1.3 prior to testing. We are using the Info.plist method of configuration - perhaps that has something to do with it?

**Comment by nabla-c0d3** [comment] 2015-08-31 21:42
We tested this on multiple devices but I will update the beta version of iOS 9 I am using, just in case. The method used for configuring TrustKit should not matter; you said you were seeing TrustKit getting initialized in the logs ?

**Comment by iragsdale** [comment] 2015-08-31 21:43
That is correct. I see the correct configuration in the logs, but I cannot get it to reject a connection, either by putting fake digest data in the configuration or by using mitmproxy to try to use a "valid" but different certificate. Both of those methods work as expected on iOS 8.

**Comment by nabla-c0d3** [comment] 2015-08-31 22:08
Ok, I will do some testing. How did you deploy TrustKit in your App ? CocoaPods, static linking or dynamic linking?

**Comment by iragsdale** [comment] 2015-08-31 22:12
CocoaPods.

**Comment by nabla-c0d3** [comment] 2015-09-02 21:19
Ok TrustKit works fine on an iPhone 4S but I was able to reproduce this on an iPhone 6; will look into it.

**Comment by nabla-c0d3** [comment] 2015-09-04 17:58
Unfortunately symbols can no longer be interposed on iOS 9 for function calls across iOS frameworks - https://twitter.com/comex/status/622232302463131648

This means that we can no longer hook SSLHandshake() and need to implement another hooking strategy (most likely at the NSURLConnection / NSURLSession level) for iOS 9. A painful change!

**Comment by dlow-yahoo-inc** [comment] 2015-10-02 02:11
Fishhook LIVES!!!
https://github.com/facebook/fishhook/issues/16

Looks like they've fixed iOS 9 support.

**Comment by ericcastro** [comment] 2015-10-02 06:54
Hi Daryl, in the link you posted I could not find any reference saying that the problem above is indeed fixed.

So far this is what we have depending on where the function is being called:
From within the app <---> to iOS framework (works on iOS9)
From witihin an iOS framework <---> to an iOS framework (doesn't work in iOS9)

See: https://twitter.com/comex/status/622232302463131648

**Comment by nabla-c0d3** [comment] 2015-10-21 15:32
This is fixed in 1.2.0.

**Closed by nabla-c0d3** 2015-10-21 15:32 UTC

**Comment by mkagenius** [comment] 2015-10-26 10:31
Hi,
When is the date for releasing this to pypi?
